version: '3'
services:
  gateway:
    image: panchem/node-runner
    command: bash -c "cd gateway && yarn --silent && yarn upgrade --silent @px/db @px/nats && nodemon -q --exec yarn start --silent"
    environment:
      NATS: "nats://nats:4222"
      REDIS: "redis://redis:6379"
    ports:
      - "3000:3000"
    volumes:
      - "$PWD:/app/"
  placement:
    image: panchem/node-runner
    command: bash -c "cd placement && yarn --silent && yarn upgrade --silent @px/db @px/nats && nodemon -q --exec yarn start --silent"
    environment:
      NATS: "nats://nats:4222"
      PGUSER: postgres
      PGHOST: postgres
      PGPASSWORD: password
    volumes:
      - "$PWD:/app/"
  query:
    image: panchem/node-runner
    command: bash -c "cd query && yarn --silent && yarn upgrade --silent @px/db @px/nats && nodemon -q --exec yarn start --silent"
    environment:
      NATS: "nats://nats:4222"
      PGUSER: postgres
      PGHOST: postgres
      PGPASSWORD: password
    volumes:
      - "$PWD:/app/"
  frontend:
    image: nginx:1.15-alpine
    volumes:
      - "$PWD/frontend:/usr/share/nginx/html:ro"
    ports:
      - "8080:80"
  nats:
    image: nats:1.2.0-linux
    ports:
      - "4222:4222"
      - "8222:8222"
      - "6222:6222"
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  postgres:
    image: postgres:10-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres