version: '3'
services:
  nats:
    image: nats:1.2.0-linux
    ports:
      - "4222:4222"
      - "8222:8222"
      - "6222:6222"
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  postgres:
    image: postgres:10-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
